### PR TITLE
Issue 1080: Location Post Update

### LINKED ISSUE #1080: Failed Locations Post Returns 200 for CDA 2025.03.05
I'm trying to write a new location and I get a 200 response that it can't parse the JSON and that it created the location. It did not create the location.

```bash
curl -X 'POST' \
  'SERVER/mvp-data/locations' \
  -H 'accept: */*' \
  -H 'Authorization: apiKey myKey' \
  -H 'Content-Type: application/json' \
  -d '{
    "office-id": "MVP",
    "name": "BallClub",
    "latitude": 47.33181227,
    "longitude": -93.8929429,
    "active": true,
    "public-name": "Ball Club River Near Ball Club, MN",
    "long-name": "Ball Club River Near Ball Club, MN",
    "timezone-name": "US/Central",
    "location-kind": "SITE",
    "nation": "US",
    "state-initial": "MN",
    "county-name": "Itasca",
    "nearest-city": "Ball Club",
    "horizontal-datum": "NAD83",
    "vertical-datum": "LOCAL",
    "map-label": "Ball Club River Near Ball Club, MN",
    "bounding-office-id": "MVP",
    "elevation-units": "ft"
}'
```

Image

### PR DESCRIPTION
**Pull request by zack-rma**
Fixes #1080

Adds `FAIL-IF-EXISTS` query parameter to locations create endpoint. Flag defaults to true.

### CODE REVIEW

File: cwms-data-api/src/test/java/cwms/cda/data/dao/basin/BasinDaoIT.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ private static void createTestLocation(String locationName, String kind) throws
         db.connection(c -> {
             try {
                 LocationsDaoImpl locationsDao = new LocationsDaoImpl(getDslContext(c, OFFICE_ID));
-                locationsDao.storeLocation(location);
+                locationsDao.storeLocation(location, false);
```
Comment (MikeNeilson) [inline cwms-data-api/src/test/java/cwms/cda/data/dao/basin/BasinDaoIT.java:175]: In the future consider providing a override that uses the default... though certainly debatable whether or not that's a good idea in the context of the our particular usage.

File: cwms-data-api/src/main/java/cwms/cda/api/LocationController.java [hunk 2]
```diff
@@ -296,8 +307,15 @@ public void create(@NotNull Context ctx) {
             String formatHeader = ctx.req.getContentType();
             ContentType contentType = Formats.parseHeader(formatHeader, Location.class);
             Location locationFromBody = Formats.parseContent(contentType, ctx.body(), Location.class);
-            locationsDao.storeLocation(locationFromBody);
-            ctx.status(HttpServletResponse.SC_OK).json("Created Location");
+            boolean failIfExists = ctx.queryParamAsClass(FAIL_IF_EXISTS, Boolean.class).getOrDefault(true);
+            locationsDao.storeLocation(locationFromBody, failIfExists);
+            ctx.status(HttpServletResponse.SC_CREATED).json("Created Location");
+        } catch (AlreadyExists e) {
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/LocationController.java]: This controller has the error handling within as it's one of the first and was created before we established the error handling within the ApiServlet exception definition.

New code should follow the new scheme for error handling.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]

File: cwms-data-api/src/test/java/cwms/cda/data/dao/basin/BasinDaoIT.java (hunk 1 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/data/dao/basin/BasinDaoIT.java:175]: I was debating the same thing, I figured I'd update the usages now to avoid keeping around the previous method. I've added a deprecated override that sets the `FAIL-IF-EXISTS` flag to false. This should allow for compatibility for downstream applications that use the locations DAO directly.

File: cwms-data-api/src/main/java/cwms/cda/api/LocationController.java (hunk 2 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationController.java]: I moved the error handling out into ApiServlet and JooqDao.

**Review by MikeNeilson — APPROVED** [review]

File: cwms-data-api/src/main/java/cwms/cda/api/LocationController.java [hunk 3]
```diff
@@ -280,6 +281,13 @@ public void getOne(@NotNull Context ctx, @NotNull String name) {
                         @OpenApiContent(from = Location.class, type = Formats.XML)
                     },
                     required = true),
```
Comment (rma-bryson) [inline cwms-data-api/src/main/java/cwms/cda/api/LocationController.java:283]: @MikeNeilson - As a general design question, does it really make sense to include a fail-if-exists parameter for a create operation? Conceptually, create implies that the resource does not already exist (at least to me, but maybe i'm wrong there) — and if it does exist, the operation should fail with exception. Conversely, update should be used when the resource already exists. So I'm questioning the need for a parameterized fail-if-exists flag for create.

Comment (MikeNeilson) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationController.java:283]: in general, no, but it's a fundamental part of our our concepts have worked in the past that just isn't mapping to the HTTP verbs as well as we'd like.
