### PR TITLE
Issue 886 - Updated LocationGroup and TimeSeriesGroup patch

### LINKED ISSUE #886: Patch Timeseries group office permission issues
closed issue https://github.com/USACE/cwms-data-api/issues/879 and opened this one since it is really a different issue.  

When patching a time series group owned by CWMS but with timeseries owned by a district office I get a user not authorized. I had to give myself write permissions to the CWMS office in order to get past that error. I don't think that is correct it should be checking the permission on the assigned-time-series office-id. At least that is they way it works in CWMS-Vue. Users don't need write permission to CWMS but to the time series office-ID.

Once I gave myself permission to the CWMS office I get a

cwms.cda.api.errors.NotFoundException: ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "Westhope" does not exist.

But Westhope does exist for MVP. I wonder if it is checking CWMS office instead of MVP for this. 

curl -X 'PATCH'
'https://cwms-data-test.cwbi.us/cwms-data/timeseries/group/SHEF%20Data%20Acquisition?replace-assigned-ts=false&office=CWMS'
-H 'accept: /'
-H 'Authorization: apikey '
-H 'Content-Type: application/json'
-d '{
"office-id": "CWMS",
"id": "SHEF Data Acquisition",
"time-series-category": {
"office-id": "CWMS",
"id": "Data Acquisition"
},
"assigned-time-series": [
{
"office-id": "MVP",
"timeseries-id": "Westhope.Stage.Inst.15Minutes.0.CEMVP-GOES-Raw",
"alias-id": "DE32E520.HG.RZZ.0015:TZ=UTC;DLTime=false;Units=ft"
}
]
}'

Also the request body in swagger needs to be updated it shows

"assigned-time-series": [
{
"officeId": "string",
"timeseriesId": "string",
"tsCode": 0,
"aliasId": "string",
"refTsId": "string",
"attribute": 0
}

It should be

"assigned-time-series": [
{
"office-id": "string",
"timeseries-id": "string",
"ts-code": 0,
"alias-id": "string",
"refTsId": "string", -> not sure what this should be.
"attribute": 0
}

### PR DESCRIPTION
**Pull request by zack-rma**
Issue #886  - Updated LocationGroup and TimeSeriesGroup patch office handling to allow for assigning non-CWMS TS/locations to a CWMS-owned group

### CODE REVIEW

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java [hunk 1]
```diff
@@ -239,31 +239,31 @@ public void create(@NotNull Context ctx) {
...
         tags = {TAG}
     )
     @Override
-    public void update(@NotNull Context ctx, String oldGroupId) {
-
+    public void update(@NotNull Context ctx, @NotNull String oldGroupId) {
         try (Timer.Context ignored = markAndTime(CREATE)) {
             DSLContext dsl = getDslContext(ctx);
-
+            final String CWMS_OFFICE = "CWMS";
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java]: This should probably be a higher level constant as the value is shared between two classes.

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java [hunk 2]
```diff
@@ -583,4 +651,313 @@ void test_add_assigned_locs() throws Exception {
             .log().ifValidationFails(LogDetail.ALL,true)
             .statusCode(is(HttpServletResponse.SC_NO_CONTENT));
     }
+
+    @Test
+    void test_patch_permissions_CWMS() throws Exception {
+        ObjectMapper mapper = new ObjectMapper();
+
+        InputStream resource = this.getClass().getResourceAsStream(
+                "/cwms/cda/api/timeseries_permission_create4.json");
```
Comment (MikeNeilson) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java]: Please provide a more meaningful name for these. I tried to skip directly to them to get a sense of data and got confused.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
Looks reasonable. would like some names changed to make review easier before digging further.

File: cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java [hunk 3]
```diff
@@ -235,31 +235,32 @@ public void create(@NotNull Context ctx) {
                 + "unassign all existing locations before assigning new locations specified in the content body "
                 + "Default: false"),
             @OpenApiParam(name = OFFICE, required = true, description = "Specifies the "
-                + "owning office of the location group to be updated"),
+                + "user office making the request"),
```
Comment (adamkorynta) [inline cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: We probably want to make this as clear as we can. It is the office used for the owning category, group and location with the caveat that for CWMS groups it is for the location only.

Comment (adamkorynta) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: The description field should also get updated to describe all the operations supported by this endpoint.

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java [hunk 4]
```diff
@@ -239,31 +239,31 @@ public void create(@NotNull Context ctx) {
                 + "unassign all existing time series before assigning new time series specified in the content body "
                 + "Default: false"),
             @OpenApiParam(name = OFFICE, required = true, description = "Specifies the "
-                + "owning office of the time series group to be updated"),
+                + "user office making the request"),
```
Comment (adamkorynta) [inline cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java]: same comment as the other controller

File: cwms-data-api/src/test/java/cwms/cda/api/LocationGroupControllerTestIT.java [hunk 5]
```diff
@@ -36,32 +44,69 @@
...
 
 import static cwms.cda.api.Controllers.*;
 import static io.restassured.RestAssured.given;
 import static org.hamcrest.Matchers.*;
 
 @Tag("integration")
-@Disabled()
 class LocationGroupControllerTestIT extends DataApiTestIT {
+    private static final Logger LOGGER = Logger.getLogger(LocationGroupControllerTestIT.class.getName());
+    private List<LocationGroup> groups = new ArrayList<>();
```
Comment (adamkorynta) [inline cwms-data-api/src/test/java/cwms/cda/api/LocationGroupControllerTestIT.java]: It looks like these field as specifically used for cleanup operations. Rename the field variable `groupsToCleanup` or something similar for clarity.

**Review by adamkorynta — CHANGES_REQUESTED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java (hunk 2 above)
Comment (adamkorynta) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java]: same

File: cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java (hunk 3 above)
Comment (MikeNeilson) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: It also seems to break the several concept we have used through CDA, though so does having an object like this owned by "CWMS" so I'm not sure there's a better way that reusing the office field in this way. 

Alternatively instead of the user needs to specifiy this here, for at least the case of assigning location, or time series in the other, it may make more sense to process them one at a time as one could provide a list of locations/timeseries each with a different office they have permissions to. Perhaps not likely now, but I could see it becoming a thing.

Comment (adamkorynta) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: The loc_alias_t is missing the office id component that would make this more explicit, the thing we thought of was that CDA could start that move by updating the location-id to a CwmsId and then iterate one by one. That would be a backwards incompatible change though given the JSON format restructure.

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java (hunk 1 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java]: Moved this constant to the Controllers class.

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java (hunk 2 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java]: Renamed to timeseries_create_SPK, hopefully this is a bit clearer

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java (hunk 4 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesGroupController.java]: I expanded the description a bit to be more representative of the actual use of the parameter

File: cwms-data-api/src/test/java/cwms/cda/api/LocationGroupControllerTestIT.java (hunk 5 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/LocationGroupControllerTestIT.java]: Renamed as suggested.

File: cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java (hunk 3 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: I added more detail to both the endpoint description and the parameter description.

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java (hunk 2 above)
Comment (adamkorynta) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java]: The confusion is the numbering. The time series all look similar, you could just edit the id at runtime to get your multiple ids in the group.

File: cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java (hunk 3 above)
Comment (adamkorynta) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: Can you add a ticket to address the above? Needing the location office to get included that's separate from the category/group office.

**Review by adamkorynta — CHANGES_REQUESTED** [review]
two outstanding comments

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java (hunk 2 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java]: I reduced the number of test JSON files from 4 to 1 with TSID replacement to differentiate the Timeseries names

File: cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java (hunk 3 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/LocationGroupController.java]: I've created a DB ticket here: [https://jira.hecdev.net/browse/CWDB-308](https://jira.hecdev.net/browse/CWDB-308)

**Review by adamkorynta — DISMISSED** [review]

**Review by MikeNeilson — DISMISSED** [review]

**Comment by zack-rma** [comment]
Rebased to fix build errors

**Review by adamkorynta — APPROVED** [review]
