### PR TITLE
CDA-40: Exception Handling Implementation Updates

### LINKED ISSUE #1106: Improve Exception/Error handling logic, heirarchy, etc
> There is no parent class that RateException can extend?  Otherwise what keeps ApiServlet from filling up with implementation specific exception types?  I would think that if we really can't think of anything more generic at the very least we should be able to make a class for Controller exceptions and another for DaoExceptions depending on where the issue is.  I don't see ApiServlet knowing how to handle RateException in any helpful or meaningfully different way than other exceptions.

_Originally posted by @rma-rripken in https://github.com/USACE/cwms-data-api/pull/1082#discussion_r2096272543_

Based on the PR discussion, we need to revisit the error handling. I think we have the crux of the right solution and some recent experience may provide us the next improvement.

### PR DESCRIPTION
**Pull request by zack-rma**
Fixes #1106 

Improves exception handling hierarchy and messages returned to users.

### CODE REVIEW

**Review by MikeNeilson — COMMENTED** [review]
Looks reasonable to me. Not sure why that test is failing as you didn't change any configuration related to it (other than some formatting).

**Comment by zack-rma** [comment]
Looks like the error message wasn't being passed to the super constructor correctly. I've fixed that and resolved some other similar message pass-through issues.

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesIdentifierDescriptorControllerTestIT.java [hunk 1]
```diff
@@ -197,6 +199,38 @@ void test_create_delete_new_LRTS_identifier(String format) throws JsonProcessing
...
+            .redirects().max(3)
+            .post("/timeseries/identifier-descriptor/")
+        .then()
+            .log().ifValidationFails(LogDetail.ALL,true)
+        .assertThat()
+            .statusCode(is(HttpServletResponse.SC_BAD_REQUEST))
+            .body("message", equalTo("Bad Request."))
+            .body("source", equalTo("User Input"))
+            .body("details.message",
+                is("Invalid Time Series Description: 12HoursLocal is not a valid duration is not a valid interval"));
```
Comment (MikeNeilson) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesIdentifierDescriptorControllerTestIT.java]: This sentence is... weird. Is the error about a duration or an interval?

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
Looks good other than one error message I simply don't understand the context of.

File: cwms-data-api/src/main/java/cwms/cda/ApiServlet.java [hunk 2]
```diff
@@ -362,22 +347,10 @@ public void init() {
                     ctx.header("X-Frame-Options", "SAMEORIGIN");
                     ctx.header("X-XSS-Protection", "1; mode=block");
                 })
-                .exception(UnsupportedFormatException.class, (e, ctx) -> {
-                    CdaError re = new CdaError(e.getMessage());
+                .exception(ApplicationException.class, (e, ctx) -> {
+                    CdaError re = new CdaError(e.getCdaErrorMessage(), e.getSource(), e.getDetails());
                     logger.atInfo().withCause(e).log(re.toString());
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/ApiServlet.java]: This new exception catch handles many previous caught exceptions. The loggers varied with the majority at info, I see one at severe, one at fine, and some weren't logged. Given these are exceptions, do you want to change the logged level to be higher than info? Warning for example?

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesIdentifierDescriptorControllerTestIT.java (hunk 1 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesIdentifierDescriptorControllerTestIT.java]: The error message builder was incorrectly appending `is not a valid interval` to the end of the error, regardless of the actual error cause coming from the database. I've removed it and updated the integration tests accordingly.

**Review by MikeNeilson — DISMISSED** [review]

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ApplicationException.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+    public String getCdaErrorMessage() {
+        return cdaErrorMessage;
+    }
+
+    public int getCdaHttpErrorCode() {
+        return cdaHttpErrorCode;
+    }
+
+    static Map<String, Serializable> buildDetailsMap(String message) {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/ApplicationException.java]: This is scoped for the usage that you have but there are sub-classes that will not be able to use this method. If you intend for the other classes to be able to use this method, then it should be scoped protected.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java [hunk 4]
```diff
@@ -1,94 +1,123 @@
...
 import java.util.Objects;
-import kotlin.random.Random;
+import java.util.UUID;
 
 /**
  * Class for reporting error to users, primary used for default error handlers for exceptions,
  * however you can initialize and return more detail to the user if it makes sense for the given
  * endpoint.
  */
 public class CdaError {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: This class should be declared as final?

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java [hunk 5]
```diff
@@ -1,94 +1,123 @@
...
-    private String message;
-    @Schema(description = "A randomly generated number to help identify your request in the logs "
+    private final String message;
+    @Schema(description = "A randomly generated UUID to help identify your request in the logs "
             + "for analysis..")
-    private String incidentIdentifier;
-    private Map<String, ? extends Object> details;
+    private final String incidentIdentifier;
+    private String source;
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: Why is source not final?

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java [hunk 6]
```diff
@@ -1,94 +1,123 @@
...
     }
 
-    public CdaError(String message, Map<String, ? extends Object> details,
+    /**
+     * Constructor with message and detail map, with option to suppress incident ID generation.
+     * @param message the error message
+     * @param details additional details about the error
+     * @param suppressIncidentId if true, suppresses the incident ID generation
+     */
+    public CdaError(String message, Map<String, Serializable> details,
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java:79]: In getDetails you return an unmodifiable details, but here you still allow for mutability given you assign the incoming ref to details. You can push the unmodifiable over to here in the constructor rather than do the unmodifiable during the get.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java [hunk 7]
```diff
@@ -1,94 +1,123 @@
...
+    }
+
     @Override
     public String toString() {
-        return String.format("%s: %s", incidentIdentifier, message);
+        String result;
+        if (source != null) {
+            result = String.format("%s: %s. Originates from %s", incidentIdentifier, message, source);
+        } else {
+            result = String.format("%s: %s", incidentIdentifier, message);
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: "%s: %s. Originates from %s"
"%s: %s"

I would include the "." delimiting the two, so "%s: %s."

Comment (rma-psmorris) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: Note that you have other messages that follow this pattern and should be corrected, "%s. %s". DeleteConflictException for example.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java [hunk 8]
```diff
@@ -24,25 +24,28 @@
...
 import java.util.Map;
+import javax.servlet.http.HttpServletResponse;
 
-public final class DeleteConflictException extends RuntimeException {
+public final class DeleteConflictException extends ApplicationException {
 
     public DeleteConflictException(String message, SQLException cause) {
-        super(message, cause);
+        super(message, "Database", "Cannot perform requested delete. "
+            + "Data is referenced elsewhere in CWMS.", HttpServletResponse.SC_CONFLICT, new HashMap<>(), cause);
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java]: Recommend revision of message, "Cannot delete this record because it is linked to other data in CWMS.”

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java [hunk 9]
```diff
@@ -1,27 +1,35 @@
...
 import java.util.ArrayList;
 import java.util.HashMap;
-import java.util.List;
 import java.util.Map;
 import java.util.Set;
 
 public class ExclusiveFieldsException extends FieldException {
     private static final String DETAIL_KEY = "Use only one of";
-    private Map<String, List<String>> details = new HashMap<>();
+    private static final String MESSAGE = "Mutually exclusive fields used.";
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: If this is generated from a request, then the error message should be: "Mutually exclusive fields were provided in the request."

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java [hunk 10]
```diff
@@ -1,27 +1,35 @@
 package cwms.cda.api.errors;
 
+import java.io.Serializable;
 import java.util.ArrayList;
 import java.util.HashMap;
-import java.util.List;
 import java.util.Map;
 import java.util.Set;
 
 public class ExclusiveFieldsException extends FieldException {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: Exceptions that you do not intend to be sub-classed should be marked final

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java [hunk 11]
```diff
@@ -1,27 +1,35 @@
...
+        details.put(DETAIL_KEY, String.join(", ", fields));
     }
 
     @Override
-    public Map<String, ? extends List<String>> getDetails() {
+    public Map<String, Serializable> getDetails() {
+        return details;
+    }
+
+    private static Map<String, Serializable> createDetails(Set<String> fields) {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: This is repeated code and could be refactored into FieldException.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java [hunk 12]
```diff
@@ -1,21 +1,25 @@
 package cwms.cda.api.errors;
 
-public class NotFoundException extends RuntimeException {
+import java.util.HashMap;
+import javax.servlet.http.HttpServletResponse;
+
+public class NotFoundException extends ApplicationException {
+    private static final String DATABASE = "Database";
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java]: Use of constant here, where as in other classes it is inline "Database". Could be refactored to all use one constant.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/RateException.java [hunk 13]
```diff
@@ -25,10 +25,13 @@
...
+import java.util.HashMap;
+import javax.servlet.http.HttpServletResponse;
 
-public final class RateException extends RuntimeException {
+public final class RateException extends ApplicationException {
 
     public RateException(String message, SQLException cause) {
-        super(message, cause);
+        super(message, "Database", "Error performing rate function: " + message,
+            HttpServletResponse.SC_BAD_REQUEST, new HashMap<>(), cause);
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/RateException.java]: Is bad request appropriate here? This a returned error from the database rate function. Is 500, SC_INTERNAL_SERVER_ERROR, more correct here?

File: cwms-data-api/src/main/java/cwms/cda/api/errors/RequiredFieldException.java [hunk 14]
```diff
@@ -9,30 +11,39 @@
...
+        details.put(MISSING_FIELDS, fieldString);
     }
 
     @Override
-    public Map<String, ? extends List<String>> getDetails() {
+    public Map<String, Serializable> getDetails() {
+        return details;
+    }
+
+    private static Map<String, Serializable> createDetails(Set<String> fields) {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/RequiredFieldException.java]: see note above on refactor

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ValueTooLongException.java [hunk 15]
```diff
@@ -26,45 +26,58 @@
...
-public final class ValueTooLongException extends RuntimeException {
-	private String parameter;
-	private int length;
-	private int maxLength;
-	private boolean suppressIncidentId = true;
+import java.util.HashMap;
+import javax.servlet.http.HttpServletResponse;
 
-	private static final String DEFAULT_ERROR = "One or more provided values exceeds the maximum length for the parameter.";
+public final class ValueTooLongException extends ApplicationException {
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/ValueTooLongException.java]: Suggest renaming this class to: FieldLengthExceededException and carry these terms into this class where appropriate.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java [hunk 16]
```diff
@@ -393,7 +393,7 @@ static InvalidItemException buildInvalidTSIDIntervalException(RuntimeException i
         if (localizedMessage != null) {
             String[] parts = localizedMessage.split("\n");
             if (parts.length > 2) {
-                return new InvalidItemException(String.format("Invalid Time Series Description: %s is not a valid interval",
+                return new InvalidItemException(String.format("Invalid Time Series Description: %s",
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java]: I would like to have this be written as: "Invalid time series description" but the error was already coded with the caps...

File: cwms-data-api/src/main/java/cwms/cda/formatters/FormattingException.java [hunk 17]
```diff
@@ -1,12 +1,21 @@
 package cwms.cda.formatters;
 
-public class FormattingException extends RuntimeException{
+import cwms.cda.api.errors.ApplicationException;
+import io.jsonwebtoken.io.IOException;
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/formatters/FormattingException.java]: Is this the correct import?

File: cwms-data-api/src/main/java/cwms/cda/security/CwmsAuthException.java [hunk 18]
```diff
@@ -1,41 +1,54 @@
...
-    public boolean suppressMessage() {
-        return this.suppress;
+    private static String getAuthErrorMessageFromCodeAndMessage(String msg, int code) {
+        switch (code) {
+            case HttpServletResponse.SC_UNAUTHORIZED:
+                return msg.isBlank() ? INVALID_USER : msg;
+            case HttpServletResponse.SC_FORBIDDEN:
+                return NOT_AUTHORIZED;
+            default:
+                return "Unknown auth error";
```
Comment (rma-psmorris) [inline cwms-data-api/src/main/java/cwms/cda/security/CwmsAuthException.java]: Auth should be fully written out as authorization to be clear that we are talking about authorization and not authentication.

**Review by rma-psmorris — CHANGES_REQUESTED** [review]
Reviewed and changes requested. There are some questions too.

File: cwms-data-api/src/main/java/cwms/cda/ApiServlet.java (hunk 2 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/ApiServlet.java]: I've added a log level field to the ApplicationException class to allow individual exceptions to retain their own logging levels. I've added it as an Optional value, so logging will only occur when it is present.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ApplicationException.java (hunk 3 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/ApplicationException.java]: Updated scope to be protected

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java (hunk 5 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: I've added a default value of "Unknown" and made source final.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java (hunk 6 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java:79]: Moved unmodifiable to constructor

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java (hunk 7 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: There was an issue with the cause message also containing a ".", resulting in double periods at the end of the message. I've updated other errors to match and added a check for messages already ending with "."

File: cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java (hunk 8 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java]: Revised as suggested.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java (hunk 9 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: Revised message as suggested.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java (hunk 10 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: Marked final

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java (hunk 11 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/ExclusiveFieldsException.java]: Refactored as suggested

File: cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java (hunk 12 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java]: Moved constant into ApplicationException class for reuse

File: cwms-data-api/src/main/java/cwms/cda/api/errors/RateException.java (hunk 13 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/RateException.java]: I had reused the existing error code, but internal server error would be more accurate. Updated as suggested.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/RequiredFieldException.java (hunk 14 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/RequiredFieldException.java]: Refactored

File: cwms-data-api/src/main/java/cwms/cda/api/errors/ValueTooLongException.java (hunk 15 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/ValueTooLongException.java]: Renamed as suggested

File: cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java (hunk 16 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java]: I've updated the error message and the appropriate tests

File: cwms-data-api/src/main/java/cwms/cda/formatters/FormattingException.java (hunk 17 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/formatters/FormattingException.java]: No, replaced with `java.io.IOException`

File: cwms-data-api/src/main/java/cwms/cda/security/CwmsAuthException.java (hunk 18 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/security/CwmsAuthException.java]: Fixed

File: cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java (hunk 4 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/CdaError.java]: Updated

**Review by zack-rma — COMMENTED** [review]
Updated classes as suggested and added improved log level handling

File: cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java (hunk 16 above)
Comment (MikeNeilson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java]: @krowvin @jbkolze thoughts on the capitalization there?

I'm with Peter on this one in that I think he's technically correct, grammar wise, but curious what other thinks.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/AlreadyExists.java [hunk 19]
```diff
@@ -1,16 +1,20 @@
 package cwms.cda.api.errors;
 
 import java.util.HashMap;
+import java.util.logging.Level;
 import javax.servlet.http.HttpServletResponse;
 
 public class AlreadyExists extends ApplicationException {
     private static final String ALREADY_EXISTS = "Already exists";
+    private static final Level LOG_LEVEL = Level.INFO;
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/AlreadyExists.java]: Lower log level. This is a common enough issue and we've already told the user, we likely *don't* need more details in the log itself.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java [hunk 20]
```diff
@@ -28,13 +28,15 @@
 import java.sql.SQLException;
 import java.util.HashMap;
 import java.util.Map;
+import java.util.logging.Level;
 import javax.servlet.http.HttpServletResponse;
 
 public final class DeleteConflictException extends ApplicationException {
+    private static final Level LOG_LEVEL = Level.INFO;
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/DeleteConflictException.java:35]: arguably same comment as AlreadyExists, but this is likely more reasonable.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java [hunk 21]
```diff
@@ -1,25 +1,30 @@
 package cwms.cda.api.errors;
 
 import java.util.HashMap;
+import java.util.logging.Level;
 import javax.servlet.http.HttpServletResponse;
 
 public class NotFoundException extends ApplicationException {
-    private static final String DATABASE = "Database";
+    private static final Level LOG_LEVEL = Level.INFO;
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/NotFoundException.java]: Same comment as AlreadyExists.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/FieldException.java [hunk 22]
```diff
@@ -3,20 +3,30 @@
 import java.io.Serializable;
 import java.util.HashMap;
 import java.util.Map;
+import java.util.Set;
+import java.util.logging.Level;
 import javax.servlet.http.HttpServletResponse;
 
 public class FieldException extends ApplicationException {
+    private static final Level LOG_LEVEL = null;
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/api/errors/FieldException.java]: why null? maybe put at lowest log level?

**Review by MikeNeilson — CHANGES_REQUESTED** [review]
Some nitpicky details, that to be fair I could be wrong about and should have discussion with others.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java (hunk 16 above)
Comment (jbkolze) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/JooqDao.java]: Agreed that in a vacuum I'd go with the lower-case version. If there are existing similar cases in the API I would just use whatever is consistent.  Realistically I wouldn't bat an eye at it either way.

Big fan of `time series` either way -- trying to move toward two separate words in new development, though i know it's not the case in a lot of legacy products.

File: cwms-data-api/src/main/java/cwms/cda/api/errors/AlreadyExists.java (hunk 19 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/AlreadyExists.java]: That's fair. I've changed it to `Level.FINE`

File: cwms-data-api/src/main/java/cwms/cda/api/errors/FieldException.java (hunk 22 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/api/errors/FieldException.java]: I had it as null since this error was not previously logged. I've updated it to `Level.FINEST`

**Review by MikeNeilson — APPROVED** [review]

**Comment by zack-rma** [comment]
Note: In a divergence from the initial design, the HTTP error codes were moved from the CdaError class to the individual exception classes, as each exception has its own thrown exception type. Since the exceptions are already being provided with the error message presented to the user, adding this data seems appropriate.

**Review by rma-psmorris — APPROVED** [review]
No further feedback
