### PR TITLE
Bug fixes/levels mixup

### LINKED ISSUE #112: /cwms-data/levels endpoint mixes up office with timezone
Example cURL:
```
curl -X 'GET' \
  'http://localhost:11524/cwms-data/levels?name=AARK.Flow.Inst.0.NWS%20Flood&office=SWT&unit=SI&datum=NAVD88&begin=01Jan1900%2000%3A00&end=01Jan1900%2000%3A00&timezone=UTC' \
  -H 'accept: */*'
```

Server-side stack:
```
Nov 18, 2021 4:24:40 PM cwms.radar.ApiServlet lambda$init$9
WARNING: error on request[-7798373712580180303]: /cwms-data/levels
org.jooq.exception.DataAccessException: SQL [{ ? = call "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (?, ?, ?, ?, ?, ?, ?, ?) }]; ORA-20010: INVALID_OFFICE_ID: "UTC" is not a valid CWMS office id
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9482
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9479
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at org.jooq_3.11.2.ORACLE11G.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:510)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:391)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:321)
	at usace.cwms.db.jooq.codegen.packages.CWMS_LEVEL_PACKAGE.call_RETRIEVE_LOCATION_LEVELS_F(CWMS_LEVEL_PACKAGE.java:1557)
	at cwms.radar.data.CwmsDataManager.getLocationLevels(CwmsDataManager.java:60)
	at cwms.radar.api.LevelsController.getAll(LevelsController.java:219)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:205)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-20010: INVALID_OFFICE_ID: "UTC" is not a valid CWMS office id
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9482
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9479
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy8.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:521)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:481)
	... 35 more
Caused by: Error : 20010, Position : 0, Sql = BEGIN :1 := "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (:2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 ) ; END;, OriginalSql = { ? = call "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (?, ?, ?, ?, ?, ?, ?, ?) }, Error Msg = ORA-20010: INVALID_OFFICE_ID: "UTC" is not a valid CWMS office id
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9482
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9479
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 58 more
```

### PR DESCRIPTION
**Pull request by rripken**
This probably wont close #112 but its a start.

### CODE REVIEW

File: cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java [hunk 1]
```diff
@@ -39,39 +32,34 @@
...
-    private final Timer createRequestTime;
-    private final Meter deleteRequest;
-    private final Timer deleteRequestTime;
-    private final Meter updateRequest;
-    private final Timer updateRequestTime;
+
 
     public LevelsController(MetricRegistry metrics){
         this.metrics=metrics;
-        String className = this.getClass().getName();
```
Comment (MikeNeilson) [inline cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java:63]: are you intentionally removing these, and if so to what purpose? (or am I blind and just not seeing that we've discovered a cleaner way?)

Comment (rripken) [reply cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java:63]: The MetricRegistry already holds references to previously created meters, timers etc so we don't have to keep our own references to them.  The method markAndTime looks up in the registry the meter and timer for the provided subject and marks the meter and starts the timer.  I did the same to the RatingController.  I think it makes things cleaner and would like to transition away from every CrudHandler having to have the meter/timer fields.

Comment (MikeNeilson) [reply cwms_radar_api/src/main/java/cwms/radar/api/LevelsController.java:63]: oh, excellent.

**Review by MikeNeilson — APPROVED** [review]
