### PR TITLE
CDA-86: Added test to verify office permission bug is resolved.

### LINKED ISSUE #1522: GET /ratings/metdata requires office, swagger spec does not
**Describe the bug**
Attempting to query for all offices in /ratings/metadata returns a trace about needing session set

**Expected behavior**
See all metadata for all offices (metadata description for office)

**Logs/Incident Identifier**

Incident: `84704e84-b161-4f16-9b92-2bd40fc6dcb8`

```json
{
  "message": "Failed to process request: org.jooq.exception.DataAccessException: SQL [{ call \"CWMS_20\".\"CWMS_ENV\".\"SET_SESSION_OFFICE_ID\" (?) }]; ORA-20998: ERROR: Unable to set a default SESSION_OFFICE_ID. The user: <CAC_USER_ID_REDACTED> either has no assigned CWMS database privileges or has privileges to more than one office. Please see your CWMS Application Admin.\nORA-06512: at \"CWMS_20.CWMS_ERR\", line 80\nORA-06512: at \"CWMS_20.CWMS_ENV\", line 85\nORA-20047: SESSION_OFFICE_ID_NOT_SET: Session office id is not set by the application\nORA-06512: at \"CWMS_20.CWMS_ERR\", line 80\nORA-06512: at \"CWMS_20.CWMS_UTIL\", line 605\nORA-01422: exact fetch returns more than requested number of rows\nORA-06512: at \"CWMS_20.CWMS_UTIL\", line 599\nORA-06512: at \"CWMS_20.CWMS_UTIL\", line 725\nORA-06512: at \"CWMS_20.CWMS_ENV\", line 79\nORA-06512: at line 1\n",
  "incidentIdentifier": "84704e84-b161-4f16-9b92-2bd40fc6dcb8",
  "source": "Unknown",
  "details": {}
}
```

**CURL Commands**
```
curl -X 'GET' \
  'https://water.dev.cwbi.us/cwms-data/ratings/metadata?_cb=1767030399722' \
  -H 'accept: application/json;version=2' \
  -H 'Cache-Control: no-cache, no-store, max-age=0' \
  -H 'Pragma: no-cache'
```

**CDA Version (please complete the following information):**
At the top of any instance of CDA you will see a version. Please provide that version.

- Version 2025.12.29-develop

### PR DESCRIPTION
**Pull request by zack-rma**
Resolves #1522.

Office issue has been resolved in previous update, this PR includes a test to verify the issue no longer exists. 

Message left without update as issue could not be replicated.

### CODE REVIEW

**Review by rma-rripken — DISMISSED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/rating/RatingSpecControllerTestIT.java [hunk 1]
```diff
@@ -101,6 +101,19 @@ void test_empty_rating_spec() throws Exception {
...
+            .log().ifValidationFails(LogDetail.ALL,true)
+            .accept(Formats.JSONV2)
+        .when()
+            .redirects().follow(true)
+            .redirects().max(3)
+            .get("/ratings/metadata")
+        .then()
+            .log().ifValidationFails(LogDetail.ALL,true)
+        .assertThat()
+            .statusCode(is(HttpServletResponse.SC_OK));
```
Comment (MikeNeilson) [inline cwms-data-api/src/test/java/cwms/cda/api/rating/RatingSpecControllerTestIT.java]: yesterdays CDA endpoints call made it pretty clear that just because we get a 200, doesn't mean we got any data. Several returned empty sets when we knew there was data.

**Review by MikeNeilson — CHANGES_REQUESTED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/rating/RatingSpecControllerTestIT.java (hunk 1 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/rating/RatingSpecControllerTestIT.java]: I've updated the test to verify the response data.

**Comment by zack-rma** [comment]
Looks like the tests are failing, I'll be looking into this further.

**Comment by zack-rma** [comment]
Expected results were not being included in the first response page. Added page size query parameter to the test.

**Review by rma-rripken — APPROVED** [review]

**Review by MikeNeilson — APPROVED** [review]
