### PR TITLE
Bugfix/cda 45 ts vertical datum

### LINKED ISSUE #1102: Implement Timeseries Endpoint Vertical Datum Conversion
Hi All,

Is specifying the parameter as NGVD29 or NAVD88 supposed to work with json version 2? It doesn't for me and I see there is a note it doesn't work w/ json version 2. If it's depreciated and not coming back maybe we should remove it from the swagger docs?

Image

### PR DESCRIPTION
**Pull request by rma-rripken**
fixes https://github.com/USACE/cwms-data-api/issues/1102

### CODE REVIEW

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 1]
```diff
@@ -1423,51 +1447,108 @@ public void create(TimeSeries input) {
...
+     * @param createAsLrts
+     * @param storeRule
+     * @param overrideProtection
+     * @throws SQLException
+     */
+    private void store(DSLContext dslContext, String officeId, String tsId, String units,
                        Timestamp versionDate, List<TimeSeries.Record> values, boolean createAsLrts,
                        StoreRule storeRule, boolean overrideProtection) throws SQLException {
-        setOffice(connection,officeId);
+        //setOffice(connection,officeId);
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: this commented out line should be removed

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+                    originalTimeSeries.getVersionDate(),
+                    originalTimeSeries.getDateVersionType())
+                    .withValues(newValues);
+        }
+        return retVal;
+    }
+
+    @NotNull
+    private static List<TimeSeries.Record> convertElevationValues(VerticalDatumInfo.Offset offset, TimeSeries retVal) {
+        Double conversionFactor = offset.getValue();
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: this is an offset not a factor

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+                    originalTimeSeries.getTimeZone(),
+                    originalTimeSeries.getVersionDate(),
+                    originalTimeSeries.getDateVersionType())
+                    .withValues(newValues);
+        }
+        return retVal;
+    }
+
+    @NotNull
+    private static List<TimeSeries.Record> convertElevationValues(VerticalDatumInfo.Offset offset, TimeSeries retVal) {
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: why is elevation in the name?  it doesn't check if the TimeSeries is elev.   Also the TimeSeries parameter being called retVal isn't a great name

Comment (rma-rripken) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: A method that took a double offset and List<TimeSeries.Record> as input and returned List<TimeSeries.Record> with offset applied would be cleaner

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+        }
+        return newValues;
+    }
+
+    static VerticalDatumInfo.Offset getOffsetForDatum(VerticalDatumInfo vdi, VerticalDatum convertTo) {
+        VerticalDatumInfo.Offset retVal = null;
+        VerticalDatumInfo.Offset[] offsets = vdi.getOffsets();
+        for (VerticalDatumInfo.Offset offset : offsets) {
+            String toDatum = offset.getToDatum();
+            if (toDatum.replaceAll("-", "").equalsIgnoreCase(convertTo.name())) {
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: This String replace/compare seems like something that could go in either VerticalDatum or VerticalDatumInfo or Offset.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+            String toDatum = offset.getToDatum();
+            if (!toDatum.replaceAll("-", "").equalsIgnoreCase(convertTo.name())) {
+                Double newOffsetValue = convertToOffsetToOriginal + offset.getValue();
+                boolean isEstimate = offset.isEstimate() || convertToOffset.isEstimate();
+                VerticalDatumInfo.Offset newOffset = new VerticalDatumInfo.Offset(isEstimate, toDatum, newOffsetValue);
+                newOffsets.add(newOffset);
+            }
+        }
+        return newOffsets.toArray(new VerticalDatumInfo.Offset[]{});
+    }
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: These two methods aren't really TimeSeries related.

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java [hunk 6]
```diff
@@ -451,6 +487,12 @@ public void getAll(@NotNull Context ctx) {
                         .build();
                 TimeSeries ts = dao.getTimeseries(cursor, pageSize, requestParameters);
 
+                if(datum != null) { //this will be null for non-elevation ts
+                    // user has requested a specific vertical datum
+                    VerticalDatum vd = VerticalDatum.valueOf(datum);  // the users request
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java:511]: If vd comes back null does that get handled?

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 7]
```diff
@@ -1423,51 +1447,108 @@ public void create(TimeSeries input) {
...
+            versionDate = Timestamp.from(input.getVersionDate().toInstant());
+        } else {
+            versionDate = null;
+        }
 
-            store(connection, input.getOfficeId(), input.getName(), input.getUnits(),
-                    versionDate, input.getValues(), createAsLrts, replaceAll, overrideProtection);
+        connection(dsl, connection -> {
+            DSLContext dslContext = getDslContext(connection, input.getOfficeId());
+                    withDefaultDatum(vd, dslContext, (conn)-> store(dslContext, input.getOfficeId(), input.getName(), input.getUnits(),
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: Can you try putting a newline after the "->" and see if the formatting looks better?  I can't decide how this bit should be.   The way it is now looks weird but I can't tell if its just b/c I'm looking at it in github or if there is a cleaner way to format.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 1 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: removed

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 2 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: updated naming

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 3 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: agreed, updated to take an offset-double and list of records as parameters

As for the elevation naming - i removed that - but also this converter only gets called if its an elevation timeseries. I believe that is determined by a metadata lookup in the dao. Is there a good way to determine if its elev as a safety check here? Maybe by parsing the ts id name?

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java (hunk 6 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java:511]: it can't come back null - an IllegalArgumentException gets thrown if it doesn't have a match

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 7 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: I think maybe it was the 'withDefaultDatum' being indented incorrectly.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 4 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: moved into Offset

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 5 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: which two methods?

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 7 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: Refactored the two lines into a method - should help a bit with readibility

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 5 above)
Comment (rma-rripken) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: convertVerticalDatumInfo and buildConvertedOffsets.   I'm thinking maybe they could go in VerticalDatumInfo? or in Offset?

**Review by rma-rripken — COMMENTED** [review]
looks good to me

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 3 above)
Comment (rma-rripken) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: IMO a second check isn't needed.   you can look at how the dao is checking the parameter - its not very sophisticated.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 5 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: ah, yeah that makes sense to me. Moved those methods. I was also able to simplify the conversion to just need an offset parameter.

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java [hunk 8]
```diff
@@ -176,6 +197,26 @@ public void create(@NotNull Context ctx) {
...
 
+    @Nullable
+    private static VerticalDatum getVerticalDatum(@Nullable TimeSeries timeSeries, @Nullable VerticalDatum vd) {
+
+        if (timeSeries != null) {
+            VerticalDatumInfo vdi = timeSeries.getVerticalDatumInfo();
+            if (vdi != null) {
+                String nativeDatum = vdi.getNativeDatum();
+                if (nativeDatum != null && !nativeDatum.isEmpty()) {
+                    if (nativeDatum.equalsIgnoreCase("OTHER")) {
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java]: Is there a constant you can use for OTHER?

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java [hunk 9]
```diff
@@ -176,6 +197,26 @@ public void create(@NotNull Context ctx) {
         }
     }
 
+    @Nullable
+    private static VerticalDatum getVerticalDatum(@Nullable TimeSeries timeSeries, @Nullable VerticalDatum vd) {
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java]: `vd` doesn't seem to be used, exception for output.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 10]
```diff
@@ -1,6 +1,16 @@
...
 
+import cwms.cda.data.dao.rsql.FieldResolver;
+import cwms.cda.data.dao.rsql.MapFieldResolver;
+import cwms.cda.data.dao.rsql.RSQLConditionBuilder;
+import cwms.cda.data.dto.filteredtimeseries.FilteredTimeSeries;
+import cwms.cda.data.dto.catalog.TimeSeriesAlias;
+import cwms.cda.helpers.DateUtils;
+
+import java.sql.Connection;
+import java.util.*;
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: Don't import *

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+
+    private static VerticalDatum getVerticalDatum(@Nullable TimeSeries timeSeries) {
+
+        VerticalDatum retVal = null;
+        if (timeSeries != null) {
+            VerticalDatumInfo vdi = timeSeries.getVerticalDatumInfo();
+            if (vdi != null) {
+                String nativeDatum = vdi.getNativeDatum();
+                if (nativeDatum != null && !nativeDatum.isEmpty()) {
+                    if (nativeDatum.equalsIgnoreCase("OTHER")) {
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: Here's that constant again

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java [hunk 12]
```diff
@@ -0,0 +1,80 @@
...
+        List<TimeSeries.Record> newValues = new ArrayList<>();
+        for (TimeSeries.Record record : originalValues) {
+            Double newValue = record.getValue() + offset;
+            TimeSeries.Record newRecord = new TimeSeries.Record(record.getDateTime(), newValue, record.getQualityCode());
+            newValues.add(newRecord);
+        }
+        return newValues;
+    }
+
+    private static VerticalDatum getVerticalDatum(@Nullable TimeSeries timeSeries) {
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: Duplicate of TimeSeriesController::getVerticalDatum.  Consolidate and use one of them, maybe use Optional for output.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 13]
```diff
@@ -437,8 +440,15 @@ protected TimeSeries getRequestedTimeSeries(String page, int pageSize, @NotNull
...
 
         TimeSeries timeseries = metadataQuery.fetchOne(tsMetadata -> {
-            String vert = (String) tsMetadata.getValue("VERTICAL_DATUM");
-            VerticalDatumInfo verticalDatumInfo = parseVerticalDatumInfo(vert);
+            String parmPart = tsMetadata.getValue("parm_part", String.class);
+            String locPart = tsMetadata.getValue("loc_part", String.class);
+
+            // Fetch vertical datum info separately only when needed
+            VerticalDatumInfo verticalDatumInfo = null;
+            if (parmPart != null && shouldFetchVerticalDatum(parmPart)) {
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: shouldFetchVerticalDatum already null checks parmPart.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 14]
```diff
@@ -1423,51 +1448,110 @@ public void create(TimeSeries input) {
...
      * @param overrideProtection honor override protection
+     * @param vd The VerticalDatum in which specified elevations are interpreted.
      *
      */
     @SuppressWarnings("unused")
     public void create(TimeSeries input,
-                       boolean createAsLrts, StoreRule storeRule, boolean overrideProtection) {
+                       boolean createAsLrts, StoreRule storeRule, boolean overrideProtection, VerticalDatum vd) {
+
+        int intervalForward = 0;
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: Unused variables

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 15]
```diff
@@ -1423,51 +1448,110 @@ public void create(TimeSeries input) {
...
+     *     then run the code and
+     *     if the datum was previously switched
+     *     then switch back to the initial datum.
+     * @param targetDatum The desired ver
+     * @param dslContext
+     * @param cr
+     * @throws Throwable
+     */
+    private void withDefaultDatum(@Nullable VerticalDatum targetDatum, DSLContext dslContext, ConnectionRunnable cr) throws Throwable {
+        final String defaultVertDatum = CWMS_LOC_PACKAGE.call_GET_DEFAULT_VERTICAL_DATUM(dslContext.configuration());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: final is implied

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java [hunk 16]
```diff
@@ -1423,51 +1448,110 @@ public void create(TimeSeries input) {
...
+
+    private void storeWithDefaultDatum(TimeSeries input, boolean createAsLrts, StoreRule replaceAll, boolean overrideProtection,
+                                       VerticalDatum vd, Connection connection, Timestamp versionDate) throws Throwable {
+        DSLContext dslContext = getDslContext(connection, input.getOfficeId());
+        withDefaultDatum(vd, dslContext, (conn)-> store(dslContext, input.getOfficeId(), input.getName(), input.getUnits(),
+                versionDate, input.getValues(), createAsLrts, replaceAll, overrideProtection));
     }
 
-    private void store(Connection connection, String officeId, String tsId, String units,
+
```
Comment (RyanM-RMA) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: Remove the comments here, it's not necessary for private functions

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 17]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+            .redirects().follow(true)
+            .redirects().max(3)
+            .post("/timeseries/")
+        .then()
+            .log().ifValidationFails(LogDetail.ALL,true)
+        .assertThat()
+            .statusCode(is(HttpServletResponse.SC_OK));
+
+
+        System.out.println("Data has been inserted for " + location);
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Logger instead of system out

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 18]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+
+        // Try again without auth
+        validatableResponse = given()
+                .log().ifValidationFails(LogDetail.ALL, true)
+                .accept(Formats.JSONV2)
+                .queryParam(OFFICE, officeId)
+                .queryParam(UNIT, "m")
+                .queryParam(NAME, ts.get(NAME).asText())
+                .queryParam(BEGIN, firstPoint)
+                .when()
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Formatting for the when, then, and assertThat is incorrect, follow the format above

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 19]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+                .redirects().follow(true)
+                .redirects().max(3)
+                .get("/timeseries/")
+                .then()
+                .log().ifValidationFails(LogDetail.ALL, true)
+                .assertThat()
+                .statusCode(is(HttpServletResponse.SC_OK));
+
+        System.out.println(validatableResponse.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 20]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+
+        validatableResponse = given()
+                .log().ifValidationFails(LogDetail.ALL, true)
+                .accept(Formats.JSONV2)
+                .queryParam(OFFICE, officeId)
+                .queryParam(UNIT, "m")
+                .queryParam(NAME, ts.get(NAME).asText())
+                .queryParam(BEGIN, firstPoint)
+                .queryParam(DATUM, "NAVD88")
+                .when()
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Formatting here

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 21]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+                .redirects().follow(true)
+                .redirects().max(3)
+                .get("/timeseries/")
+                .then()
+                .log().ifValidationFails(LogDetail.ALL, true)
+                .assertThat()
+                .statusCode(is(HttpServletResponse.SC_OK));
+
+        System.out.println(validatableResponse.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 22]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+            .redirects().max(3)
+            .post("/timeseries/")
+        .then()
+            .log().ifValidationFails(LogDetail.ALL, true)
+        .assertThat()
+            .statusCode(is(HttpServletResponse.SC_OK));
+
+        // GET after scenario 1 and verify values equal input (NAVD88 native)
+        ValidatableResponse vr1 = doGet.get();
+        System.out.println("1:" + vr1.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 23]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+            .when()
+                .redirects().follow(true)
+                .redirects().max(3)
+                .get("/timeseries/")
+            .then()
+                .log().ifValidationFails(LogDetail.ALL, true)
+            .assertThat()
+                .statusCode(is(HttpServletResponse.SC_OK));
+
+        System.out.println(validatableResponse.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 24]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+            .redirects().max(3)
+            .post("/timeseries/")
+        .then()
+            .log().ifValidationFails(LogDetail.ALL, true)
+        .assertThat()
+            .statusCode(is(HttpServletResponse.SC_OK));
+
+        // GET after scenario 2 and verify values equal input; also capture NGVD29 offset
+        ValidatableResponse vr2 = doGet.get();
+        System.out.println("2:" + vr2.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 25]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+
+        // Compute expected NAVD88 = NGVD29 - offset(NAVD88->NGVD29)
+        java.util.List<Double> expectedNavd88 = new java.util.ArrayList<>();
+        for (Double v : inputValues) {
+            expectedNavd88.add(v - offsetToNgvd29);
+        }
+
+        // GET after scenario 3 and verify the conversion was applied
+        ValidatableResponse vr3 = doGet.get();
+        System.out.println("3:" + vr3.extract().asString());
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Use logger

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java [hunk 26]
```diff
@@ -1797,4 +1803,388 @@ enum GetAllTest
...
+
+        ValidatableResponse validatableResponseConverted = given()
+                .log().ifValidationFails(LogDetail.ALL, true)
+                .accept(Formats.JSONV2)
+                .queryParam(OFFICE, officeId)
+                .queryParam(UNIT, "m")
+                .queryParam(NAME, ts.get(NAME).asText())
+                .queryParam(BEGIN, firstPoint)
+                .queryParam(DATUM, "NGVD29")
+                .when()
```
Comment (RyanM-RMA) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: Formatting here

**Review by RyanM-RMA — CHANGES_REQUESTED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 26 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: fixed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 25 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 24 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 23 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 22 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: don't see a good reason to keep these print statements. I'm assuming Ryan Ripken had them when he was testing locally. Deleting as we test the responses in the asserts

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 12 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: updated to be static and re-used

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 21 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 20 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: fixed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 19 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 18 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: fixed

File: cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java (hunk 17 above)
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeseriesControllerTestIT.java]: removed

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 16 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: removed javadoc

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 15 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: removed final

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 14 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: removed

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 13 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: removed null check

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java (hunk 11 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesVerticalDatumConverter.java]: references enum now

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java (hunk 10 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesDaoImpl.java]: cleaned up imports

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java (hunk 9 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java]: updated this code to be more functional by returning an Optional with an orElse to default to vd

File: cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java (hunk 8 above)
Comment (rma-bryson) [reply cwms-data-api/src/main/java/cwms/cda/api/TimeSeriesController.java]: moving this into the VerticalDatum enum

**Review by RyanM-RMA — DISMISSED** [review]

**Review by RyanM-RMA — DISMISSED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java
Comment (rma-rripken) [inline cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java:1]: This is a get request - why are you adding authorization?

Comment (rma-rripken) [reply cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java:1]: I see that the code in develop has it too but in my opinion it shouldn't.  How does this fail if it isn't present?

**Review by RyanM-RMA — DISMISSED** [review]

File: cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java
Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java:1]: I thought maybe I did something when i was rebasing so the intent there was to just make this match what was in develop because it seemed unrelated to the work in this ticket - but I can remove it

Comment (rma-bryson) [reply cwms-data-api/src/test/java/cwms/cda/api/LocationControllerTestIT.java:1]: removed it in latest push

**Review by RyanM-RMA — APPROVED** [review]
