### PR TITLE
CDA-29: Fix TimeSeries group request slower than expected

### LINKED ISSUE #1022: TimeSeries group request slower than expected
```
curl -X 'GET' \
  'https://<host>/cwms-data/timeseries/group?office=NWDP&include-assigned=true&timeseries-category-like=NWP_A.%2A' \
  -H 'accept: application/json'
```

The returned result is rather large, but should be even then should be relatively fast given what the data is.

Tested on cwbi-test and future prod, equally slow on both.

### PR DESCRIPTION
**Pull request by zack-rma**
Fixes #1022

Update in progress to TimeSeries group retrieval query.

### CODE REVIEW

**Comment by rma-rripken** [comment]
The order-by should probably be:  category_office_id, category_id, group_office_id, group_id, and then the attribute.   You might consider DSL.multiset.

**Comment by rma-rripken** [comment]
or it could be multiple queries.   One to find the distinct keys (category_office_id, category_id, group_office_id, group_id)  Then another query to find assignments groupedBy keys ordered by attribute.

**Comment by rma-rripken** [comment]
We might also consider adding paging.  I suggest paging by fixed number of groups per page, keep entire group within one page and not try to count assignments.  The LOE didn't include adding paging.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 1]
```diff
@@ -128,30 +131,49 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWhere(Condition whereCond, Stri
...
+                catGrp.CAT_DB_OFFICE_ID,
+                catGrp.TS_CATEGORY_ID,
+                catGrp.TS_CATEGORY_DESC,
+                catGrp.GRP_DB_OFFICE_ID,
+                catGrp.TS_GROUP_ID,
+                catGrp.TS_GROUP_DESC,
+                catGrp.SHARED_TS_ALIAS_ID,
+                catGrp.SHARED_REF_TS_ID,
+
+                // Use multiset to efficiently fetch localized grpAssgn records
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: remove this comment

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 2]
```diff
@@ -128,30 +131,49 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWhere(Condition whereCond, Stri
...
+            .from(catGrp)
             .where(whereCond)
-            .and(whereCondGrpCat)
-            .orderBy(catGrp.TS_GROUP_ID, grpAssgn.ATTRIBUTE);
+            .and(whereCondGrpCat);
 
-        logger.fine(() -> query.getSQL(ParamType.INLINED));
 
-        List<Pair<TimeSeriesGroup, AssignedTimeSeries>> assignments =
+        logger.severe(() -> query.getSQL(ParamType.INLINED));
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: shouldn't be severe

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 3]
```diff
@@ -128,30 +131,49 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWhere(Condition whereCond, Stri
...
+
+        List<Pair<TimeSeriesGroup, List<AssignedTimeSeries>>> assignments =
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: If I understand multiset there is probably a way to go right from the query to the Map<group, list> type that we want for return.   If you can't figure it out in a couple minutes just keep what you have

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 4]
```diff
@@ -183,23 +205,33 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWithoutAssigned(Condition where
...
+    private List<AssignedTimeSeries> buildAssignedTimeSeries(org.jooq.Record queryRecord) {
+        List<AssignedTimeSeries> retval = new ArrayList<>();
+
+        String assignRecord = queryRecord.get("assignments", String.class);
+        if (assignRecord != null) {
+            try {
+                JSONArray jsonArr = (JSONArray) new JSONParser().parse(assignRecord);
+                for (Object obj : jsonArr) {
+
+                    JSONArray json = (JSONArray) obj;
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Curious.  We haven't gotten results as string and then parsed them as JSON anywhere else.  I respect the hustle but I prefer adding a mapper and pulling explicit fields out of the result and feeding them into a method reference to do the Result->DTO mapping.

Comment (rma-rripken) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: I'm going to remember this trick for more desperate situations

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 5]
```diff
@@ -128,30 +131,49 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWhere(Condition whereCond, Stri
...
+                            grpAssgn.TS_ID,
+                            grpAssgn.DB_OFFICE_ID,
+                            grpAssgn.ATTRIBUTE,
+                            grpAssgn.ALIAS_ID,
+                            grpAssgn.REF_TS_ID
+                        )
+                        .from(grpAssgn)
+                        .where(joinCond)
+                        .orderBy(grpAssgn.ATTRIBUTE) // Localized ordering inside the group
+                ).as("assignments") // Alias for the resulting nested collection
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: instead of .as("assignments")   I think you can do something like 
.convertFrom(rs -> rs.map(this::buildAssignedTimeSeries))

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 4 above)
Comment (MikeNeilson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Arguably worth doing *if* the resulting speed justifies it. But really only then.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 2 above)
Comment (MikeNeilson) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Does anyone know if java.util.logging can do a "also include user configuration?"

If so we should really just implement that, we all do this when finding problems... and we all accidentally leave it in; I'm as guilty of that as anyone.

If not, perhaps we should consider a different logger for the tests... well, and actually using a logging facade... but that's a whole other question than this PR.

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java [hunk 6]
```diff
@@ -1666,6 +1666,6 @@ void testRetrievalTiming() {
         .assertThat()
             .statusCode(is(HttpServletResponse.SC_OK))
             .body("assigned-time-series.size()", greaterThan(0))
-            .time(lessThan(250L)); // should be pretty quick, under 0.5 seconds. Old query was ~3 seconds
+            .time(lessThan(500L)); // should be pretty quick, under 0.5 seconds. Old query was ~3 seconds
```
Comment (MikeNeilson) [inline cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java:1669]: I certainly like 250ms better, but I'll concede that 500 is a large improvement over 3s.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 7]
```diff
@@ -183,23 +205,33 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWithoutAssigned(Condition where
...
+                    Integer attr = null;
+                    if (attrBD != null) {
+                        attr = attrBD.intValue();
+                    }
+
+                    retval.add(new AssignedTimeSeries(officeId, timeseriesId, aliasId, refTsId, attr));
+                }
+            } catch (ParseException e) {
+                logger.severe(() -> "Error parsing assigned time series JSON: " + e.getMessage());
+                throw new RuntimeException(e);
```
Comment (MikeNeilson) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Don't we have an exception system to handle this more cleanly?

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 3 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Updated mapping method to use Result type

File: cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java (hunk 6 above)
Comment (zack-rma) [reply cwms-data-api/src/test/java/cwms/cda/api/TimeSeriesGroupControllerTestIT.java:1669]: I was seeing closer to 250 regularly, but the occasional ~260ms was causing failure. I set it to 500 to be safe.

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 1 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Removed

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 5 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Updated as suggested

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 2 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Reverted to fine

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 4 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Removed and transitioned to using Record type

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java (hunk 7 above)
Comment (zack-rma) [reply cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java]: Removed

**Comment by rma-rripken** [comment]
I think it can be even cleaner.   I don't think the multiset needs to sort on all those fields. The advantage of the multiset is that the sorting can happen separately.
We shouldn't have to do the dance with the List of Pair<>, we should be able to just map to the final results.

Can you try something like this? 

```
        SelectSeekStep4<Record9<String, String, String, String, String, String, String, String, List<AssignedTimeSeries>>, 
                String, String, String, String> query = 
                dsl.select(
                        catGrp.CAT_DB_OFFICE_ID,
                        catGrp.TS_CATEGORY_ID,
                        catGrp.TS_CATEGORY_DESC,
                        catGrp.GRP_DB_OFFICE_ID,
                        catGrp.TS_GROUP_ID,
                        catGrp.TS_GROUP_DESC,
                        catGrp.SHARED_TS_ALIAS_ID,
                        catGrp.SHARED_REF_TS_ID,
                        DSL.multiset(
                                dsl.select(
                                                grpAssgn.DB_OFFICE_ID,
                                                grpAssgn.TS_ID,
                                                grpAssgn.ATTRIBUTE,
                                                grpAssgn.ALIAS_ID,
                                                grpAssgn.REF_TS_ID
                                        )
                                        .from(grpAssgn)
                                        .where(joinCond)
                                        .orderBy(grpAssgn.ATTRIBUTE)
                        ).convertFrom(rs -> rs.map(this::buildAssignedTimeSeries))
                )
                .from(catGrp)
                .where(whereCond)
                .and(whereCondGrpCat)
                .orderBy(
                        catGrp.CAT_DB_OFFICE_ID,
                        catGrp.TS_CATEGORY_ID,
                        catGrp.GRP_DB_OFFICE_ID,
                        catGrp.TS_GROUP_ID
                );

        logger.fine(() -> query.getSQL(ParamType.INLINED));

        RecordMapper<? super Record9<String, String, String, String, String, String, String, String, List<AssignedTimeSeries>>, TimeSeriesGroup> mapperToTimeSeriesGroup =
                queryRecord -> {
                    TimeSeriesGroup group = buildTimeSeriesGroup(queryRecord);
                    List<AssignedTimeSeries> assignedTS = (List<AssignedTimeSeries>) queryRecord.get("multiset");

                    return new TimeSeriesGroup(group, assignedTS);
                };

        return query.fetch(mapperToTimeSeriesGroup);
```

File: cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java [hunk 8]
```diff
@@ -151,35 +138,29 @@ private List<TimeSeriesGroup> getTimeSeriesGroupsWhere(Condition whereCond, Stri
...
+                    return new TimeSeriesGroup(group, assignedTS);
+                };
 
-        List<TimeSeriesGroup> retval = new ArrayList<>();
-        for (final Map.Entry<TimeSeriesGroup, List<AssignedTimeSeries>> entry : map.entrySet()) {
-            List<AssignedTimeSeries> assigned = entry.getValue();
-            retval.add(new TimeSeriesGroup(entry.getKey(), assigned));
-        }
-        return retval;
+        return query.fetch(mapperToTimeSeriesGroup);
```
Comment (rma-rripken) [inline cwms-data-api/src/main/java/cwms/cda/data/dao/TimeSeriesGroupDao.java:163]: That looks much cleaner.  Hopefully the performance is still there.

**Review by rma-rripken — APPROVED** [review]
